/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_tiffannyvarela;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author tiffa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarusuario = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_nusuario = new javax.swing.JTextField();
        txt_contranueva = new javax.swing.JTextField();
        btn_color = new javax.swing.JButton();
        date_fnacimiento = new com.toedter.calendar.JDateChooser();
        btn_agregarusuario = new javax.swing.JButton();
        jd_ingresar = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_usuario = new javax.swing.JTextField();
        jpass_contrasena = new javax.swing.JPasswordField();
        jd_mazo1 = new javax.swing.JDialog();
        cmb_mazo1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_mazo1 = new javax.swing.JTree();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txt_coste1 = new javax.swing.JTextField();
        jd_mazo2 = new javax.swing.JDialog();
        btn_agregarcarta2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_mazo2 = new javax.swing.JTree();
        jLabel18 = new javax.swing.JLabel();
        cmb_mazo2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jd_mazo3 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_mazo3 = new javax.swing.JTree();
        btn_agregarcarta3 = new javax.swing.JButton();
        cmb_mazo3 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jd_crearcarta = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_danio = new javax.swing.JTextField();
        txt_pvida = new javax.swing.JTextField();
        cmb_cartas = new javax.swing.JComboBox<>();
        btn_agregarcarta = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_nombrecarta = new javax.swing.JTextField();
        popup_mostar1 = new javax.swing.JPopupMenu();
        jmi_mostrar1 = new javax.swing.JMenuItem();
        jd_m1 = new javax.swing.JDialog();
        jd_crearclan = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btn_crearclan = new javax.swing.JButton();
        txt_nombreequipo = new javax.swing.JTextField();
        date_creacion = new com.toedter.calendar.JDateChooser();
        cmb_usuariolider = new javax.swing.JComboBox<>();
        cmb_tipoclan = new javax.swing.JComboBox<>();
        jd_ingresarclan = new javax.swing.JDialog();
        cmb_usuariolider1 = new javax.swing.JComboBox<>();
        cmb_clanes = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_clan = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenu_usuario = new javax.swing.JMenu();
        jmi_agregar = new javax.swing.JMenuItem();
        jmi_ingresar = new javax.swing.JMenuItem();
        jmenu_carta = new javax.swing.JMenu();
        jmi_crearcarta = new javax.swing.JMenuItem();
        jmenu_mazo = new javax.swing.JMenu();
        jmi_mazo1 = new javax.swing.JMenuItem();
        jmi_mazo2 = new javax.swing.JMenuItem();
        jmi_mazo3 = new javax.swing.JMenuItem();
        jmenu_clan = new javax.swing.JMenu();
        jmi_crearclan = new javax.swing.JMenuItem();
        jmi_ingresarclan = new javax.swing.JMenuItem();

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Agregar Usuario");

        jLabel6.setText("Nombre");

        jLabel7.setText("Apellido");

        jLabel8.setText("Nombre de usuario");

        jLabel9.setText("Contrasena");

        jLabel10.setText("Fecha de nacimiento");

        jLabel12.setText("Color");

        btn_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorActionPerformed(evt);
            }
        });

        btn_agregarusuario.setText("Agregar");
        btn_agregarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarusuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarusuarioLayout = new javax.swing.GroupLayout(jd_agregarusuario.getContentPane());
        jd_agregarusuario.getContentPane().setLayout(jd_agregarusuarioLayout);
        jd_agregarusuarioLayout.setHorizontalGroup(
            jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarusuarioLayout.createSequentialGroup()
                .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarusuarioLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarusuarioLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(date_fnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarusuarioLayout.createSequentialGroup()
                                .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(49, 49, 49)
                                .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nombre)
                                    .addComponent(txt_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                                .addGap(173, 173, 173)
                                .addComponent(btn_agregarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarusuarioLayout.createSequentialGroup()
                                .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_contranueva, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(txt_nusuario)))
                            .addGroup(jd_agregarusuarioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(38, 38, 38)
                                .addComponent(btn_color, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_agregarusuarioLayout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel4)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jd_agregarusuarioLayout.setVerticalGroup(
            jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarusuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_agregarusuarioLayout.createSequentialGroup()
                        .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_agregarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_nusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_contranueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(jLabel10))
                    .addComponent(date_fnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jd_agregarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btn_color, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Ingresar");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contrasena");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ingresarLayout = new javax.swing.GroupLayout(jd_ingresar.getContentPane());
        jd_ingresar.getContentPane().setLayout(jd_ingresarLayout);
        jd_ingresarLayout.setHorizontalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresarLayout.createSequentialGroup()
                .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ingresarLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(jd_ingresarLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_usuario)
                            .addComponent(jpass_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addGroup(jd_ingresarLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jd_ingresarLayout.setVerticalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpass_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setText("Mazo 1");

        jLabel17.setText("Cartas");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Cartas");
        jt_mazo1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_mazo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_mazo1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_mazo1);

        jButton2.setText("Agregar Carta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel27.setText("Coste");

        txt_coste1.setEditable(false);

        javax.swing.GroupLayout jd_mazo1Layout = new javax.swing.GroupLayout(jd_mazo1.getContentPane());
        jd_mazo1.getContentPane().setLayout(jd_mazo1Layout);
        jd_mazo1Layout.setHorizontalGroup(
            jd_mazo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mazo1Layout.createSequentialGroup()
                .addGroup(jd_mazo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mazo1Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel16))
                    .addGroup(jd_mazo1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel17)
                        .addGap(45, 45, 45)
                        .addComponent(cmb_mazo1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_coste1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mazo1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mazo1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jd_mazo1Layout.setVerticalGroup(
            jd_mazo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mazo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(55, 55, 55)
                .addGroup(jd_mazo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_mazo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel27)
                    .addComponent(txt_coste1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jd_mazo2.setPreferredSize(new java.awt.Dimension(717, 524));

        btn_agregarcarta2.setText("Agregar Carta");
        btn_agregarcarta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcarta2ActionPerformed(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Cartas");
        jt_mazo2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_mazo2);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("Mazo 2");

        jLabel19.setText("Cartas");

        javax.swing.GroupLayout jd_mazo2Layout = new javax.swing.GroupLayout(jd_mazo2.getContentPane());
        jd_mazo2.getContentPane().setLayout(jd_mazo2Layout);
        jd_mazo2Layout.setHorizontalGroup(
            jd_mazo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mazo2Layout.createSequentialGroup()
                .addGroup(jd_mazo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mazo2Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel18))
                    .addGroup(jd_mazo2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel19)
                        .addGap(45, 45, 45)
                        .addComponent(cmb_mazo2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mazo2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btn_agregarcarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mazo2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jd_mazo2Layout.setVerticalGroup(
            jd_mazo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mazo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(55, 55, 55)
                .addGroup(jd_mazo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_mazo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(36, 36, 36)
                .addComponent(btn_agregarcarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jd_mazo3.setPreferredSize(new java.awt.Dimension(717, 524));

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Cartas");
        jt_mazo3.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_mazo3);

        btn_agregarcarta3.setText("Agregar Carta");
        btn_agregarcarta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcarta3ActionPerformed(evt);
            }
        });

        jLabel20.setText("Cartas");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel21.setText("Mazo 3");

        javax.swing.GroupLayout jd_mazo3Layout = new javax.swing.GroupLayout(jd_mazo3.getContentPane());
        jd_mazo3.getContentPane().setLayout(jd_mazo3Layout);
        jd_mazo3Layout.setHorizontalGroup(
            jd_mazo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mazo3Layout.createSequentialGroup()
                .addGroup(jd_mazo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mazo3Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel21))
                    .addGroup(jd_mazo3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel20)
                        .addGap(45, 45, 45)
                        .addComponent(cmb_mazo3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mazo3Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btn_agregarcarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mazo3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jd_mazo3Layout.setVerticalGroup(
            jd_mazo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mazo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(55, 55, 55)
                .addGroup(jd_mazo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_mazo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(36, 36, 36)
                .addComponent(btn_agregarcarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jd_crearcarta.setPreferredSize(new java.awt.Dimension(717, 524));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Crear Cartas");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Danio");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Puntos de vida");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Carta");

        txt_danio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txt_pvida.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        cmb_cartas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmb_cartas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione carta", "Minipekka", "Montapuerco", "Golem", "Lenador", "Dragon infernal", "Dragon", "Gigante noble", "Pandilla de duendes" }));

        btn_agregarcarta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_agregarcarta.setText("Agregar");
        btn_agregarcarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcartaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Nombre");

        txt_nombrecarta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jd_crearcartaLayout = new javax.swing.GroupLayout(jd_crearcarta.getContentPane());
        jd_crearcarta.getContentPane().setLayout(jd_crearcartaLayout);
        jd_crearcartaLayout.setHorizontalGroup(
            jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearcartaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(281, 281, 281))
            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearcartaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(42, 42, 42)
                                .addComponent(cmb_cartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_pvida))
                            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel11))
                                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crearcartaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_danio, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearcartaLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(txt_nombrecarta, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jd_crearcartaLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(btn_agregarcarta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jd_crearcartaLayout.setVerticalGroup(
            jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcartaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_nombrecarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_danio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_pvida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jd_crearcartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmb_cartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregarcarta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jmi_mostrar1.setText("Mostrar");
        jmi_mostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mostrar1ActionPerformed(evt);
            }
        });
        popup_mostar1.add(jmi_mostrar1);

        javax.swing.GroupLayout jd_m1Layout = new javax.swing.GroupLayout(jd_m1.getContentPane());
        jd_m1.getContentPane().setLayout(jd_m1Layout);
        jd_m1Layout.setHorizontalGroup(
            jd_m1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_m1Layout.setVerticalGroup(
            jd_m1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jd_crearclan.setPreferredSize(new java.awt.Dimension(717, 524));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel22.setText("Crear Clan");

        jLabel23.setText("Nombre");

        jLabel24.setText("Fecha de creacion");

        jLabel25.setText("Usuario lider");

        jLabel26.setText("Tipo");

        btn_crearclan.setText("Crear clan");
        btn_crearclan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearclanActionPerformed(evt);
            }
        });

        cmb_tipoclan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar tipo", "Bronce", "Plata", "Oro", "Legendario" }));

        javax.swing.GroupLayout jd_crearclanLayout = new javax.swing.GroupLayout(jd_crearclan.getContentPane());
        jd_crearclan.getContentPane().setLayout(jd_crearclanLayout);
        jd_crearclanLayout.setHorizontalGroup(
            jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearclanLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearclanLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(44, 44, 44)
                        .addComponent(cmb_tipoclan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearclanLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(33, 33, 33)
                        .addComponent(cmb_usuariolider, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearclanLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(30, 30, 30)
                        .addComponent(date_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearclanLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(30, 30, 30)
                        .addComponent(txt_nombreequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearclanLayout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_crearclan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(295, 295, 295))
        );
        jd_crearclanLayout.setVerticalGroup(
            jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearclanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(56, 56, 56)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txt_nombreequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(date_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cmb_usuariolider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_crearclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cmb_tipoclan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_crearclan, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jd_ingresarclan.setPreferredSize(new java.awt.Dimension(717, 524));

        jLabel28.setText("Usuarios");

        jLabel29.setText("Clanes");

        jl_clan.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_clan);

        jButton5.setText("Agregar Lista");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ingresarclanLayout = new javax.swing.GroupLayout(jd_ingresarclan.getContentPane());
        jd_ingresarclan.getContentPane().setLayout(jd_ingresarclanLayout);
        jd_ingresarclanLayout.setHorizontalGroup(
            jd_ingresarclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresarclanLayout.createSequentialGroup()
                .addGroup(jd_ingresarclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ingresarclanLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jd_ingresarclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(64, 64, 64)
                        .addGroup(jd_ingresarclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_usuariolider1, 0, 188, Short.MAX_VALUE)
                            .addComponent(cmb_clanes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ingresarclanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jd_ingresarclanLayout.setVerticalGroup(
            jd_ingresarclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresarclanLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jd_ingresarclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_usuariolider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jd_ingresarclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_clanes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGroup(jd_ingresarclanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ingresarclanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ingresarclanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmenu_usuario.setText("Usuario");

        jmi_agregar.setText("Agregar");
        jmi_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarActionPerformed(evt);
            }
        });
        jmenu_usuario.add(jmi_agregar);

        jmi_ingresar.setText("Ingresar");
        jmi_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ingresarActionPerformed(evt);
            }
        });
        jmenu_usuario.add(jmi_ingresar);

        jMenuBar1.add(jmenu_usuario);

        jmenu_carta.setText("Cartas");
        jmenu_carta.setEnabled(false);

        jmi_crearcarta.setText("Crear");
        jmi_crearcarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearcartaActionPerformed(evt);
            }
        });
        jmenu_carta.add(jmi_crearcarta);

        jMenuBar1.add(jmenu_carta);

        jmenu_mazo.setText("Mazo");
        jmenu_mazo.setEnabled(false);

        jmi_mazo1.setText("Mazo 1");
        jmi_mazo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mazo1ActionPerformed(evt);
            }
        });
        jmenu_mazo.add(jmi_mazo1);

        jmi_mazo2.setText("Mazo 2");
        jmi_mazo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mazo2ActionPerformed(evt);
            }
        });
        jmenu_mazo.add(jmi_mazo2);

        jmi_mazo3.setText("Mazo 3");
        jmi_mazo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mazo3ActionPerformed(evt);
            }
        });
        jmenu_mazo.add(jmi_mazo3);

        jMenuBar1.add(jmenu_mazo);

        jmenu_clan.setText("Clan");
        jmenu_clan.setEnabled(false);

        jmi_crearclan.setText("Crear");
        jmi_crearclan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearclanActionPerformed(evt);
            }
        });
        jmenu_clan.add(jmi_crearclan);

        jmi_ingresarclan.setText("Ingresar");
        jmi_ingresarclan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ingresarclanActionPerformed(evt);
            }
        });
        jmenu_clan.add(jmi_ingresarclan);

        jMenuBar1.add(jmenu_clan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_crearclanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearclanActionPerformed
        // TODO add your handling code here:
        jd_crearclan.setModal(true);
        jd_crearclan.pack();
        jd_crearclan.setLocationRelativeTo(this);
        jd_crearclan.setVisible(true);
    }//GEN-LAST:event_jmi_crearclanActionPerformed

    private void jmi_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarActionPerformed
        // TODO add your handling code here:
        jd_agregarusuario.setModal(true);
        jd_agregarusuario.pack();
        jd_agregarusuario.setLocationRelativeTo(this);
        jd_agregarusuario.setVisible(true);
    }//GEN-LAST:event_jmi_agregarActionPerformed

    private void btn_agregarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarusuarioActionPerformed
        // TODO add your handling code here:
        String nombre, apellido, n_usuario, contra;
        int edad;
        Color color = Color.RED;
        Date fecha_nac;
        
        nombre=txt_nombre.getText();
        apellido=txt_apellido.getText();
        n_usuario=txt_nusuario.getText();
        contra=txt_contranueva.getText();
        fecha_nac=date_fnacimiento.getDate();
       
        edad=(int)(((new Date()).getTime() - fecha_nac.getTime()) / (1000 * 60 * 60 * 24)/365);
        
        Usuario x = new Usuario(nombre, apellido, n_usuario, contra, fecha_nac, edad, color);
        usuarios.add(x);
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_usuariolider.getModel();
        modelo.addElement(x);
        cmb_usuariolider.setModel(modelo);
        cmb_usuariolider1.setModel(modelo);
        System.out.println(edad);
        System.out.println(usuarios);
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_contranueva.setText("");
        txt_nusuario.setText("");
        date_fnacimiento.setDate(new Date());
        btn_color.setBackground(Color.RED);
        
        
        jd_agregarusuario.setVisible(false);
    }//GEN-LAST:event_btn_agregarusuarioActionPerformed

    private void btn_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorActionPerformed
        // TODO add your handling code here:
         btn_color.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_btn_colorActionPerformed

    private void jmi_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ingresarActionPerformed
        // TODO add your handling code here:
        jd_ingresar.setModal(true);
        jd_ingresar.pack();
        jd_ingresar.setLocationRelativeTo(this);
        jd_ingresar.setVisible(true);
    }//GEN-LAST:event_jmi_ingresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            for (int i = 0; i < usuarios.size(); i++) {
            if (txt_usuario.getText().equals(((Usuario)usuarios.get(i)).getN_usuario())&&jpass_contrasena.getText().equals(((Usuario)usuarios.get(i)).getContrasena())) {
                jmenu_clan.setEnabled(true);
                jmenu_mazo.setEnabled(true);
               jmenu_carta.setEnabled(true);
                jd_ingresar.setVisible(false);
                 txt_usuario.setText("");
                jpass_contrasena.setText("");
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_ingresar, "Usuario y contrasena no validos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmi_crearcartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearcartaActionPerformed
        // TODO add your handling code here:
        jd_crearcarta.setModal(true);
        jd_crearcarta.pack();
        jd_crearcarta.setLocationRelativeTo(this);
        jd_crearcarta.setVisible(true);
    }//GEN-LAST:event_jmi_crearcartaActionPerformed

    private void btn_agregarcartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcartaActionPerformed
        // TODO add your handling code here:
        String nombre, objetivo = null, velocidad = null,tipo = null;
        int dano, p_vida, c_elixir = 0;
        nombre = txt_nombrecarta.getText();
        dano = Integer.parseInt(txt_danio.getText());
        p_vida = Integer.parseInt(txt_danio.getText());
        int opc=cmb_cartas.getSelectedIndex();
        Carta x = new Carta();
        if (opc==1) {
            x=new Minipekka(objetivo, velocidad, c_elixir, tipo, nombre, dano, p_vida);
        }
        
        if (opc==2) {
            x=new Montapuerco(objetivo, velocidad, c_elixir, tipo, nombre, dano, p_vida);
        }
        
        if (opc==3) {
            x=new Golem(objetivo, velocidad, c_elixir, tipo, nombre, dano, p_vida);
        }
        
        if (opc==4) {
            x=new Lenador(objetivo, velocidad, c_elixir, tipo, nombre, dano, p_vida);
        }
        
        if (opc==5) {
            x=new Dragon_inf(objetivo, velocidad, c_elixir, tipo, nombre, dano, p_vida);
        }
        
        if (opc==6) {
            x=new Dragon(objetivo, velocidad, c_elixir, tipo, nombre, dano, p_vida);
        }
        
        if (opc==7) {
            x=new Gigante_nob(nombre, dano, p_vida, objetivo, velocidad, c_elixir, tipo);
        }
        
        if (opc==8) {
            x=new Pandilla_duendes(nombre, dano, p_vida, objetivo, velocidad, c_elixir, tipo);
        }
        cartas.add(x);
        DefaultComboBoxModel modelo =(DefaultComboBoxModel) cmb_mazo1.getModel();
        modelo.addElement(x);
        cmb_mazo1.setModel(modelo);
        cmb_mazo2.setModel(modelo);
        cmb_mazo3.setModel(modelo);
        
        txt_nombrecarta.setText("");
        txt_danio.setText("");
        txt_pvida.setText("");
        cmb_cartas.setSelectedIndex(0);
    }//GEN-LAST:event_btn_agregarcartaActionPerformed

    private void jmi_mazo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mazo1ActionPerformed
        // TODO add your handling code here:
        jd_mazo1.setModal(true);
        jd_mazo1.pack();
        jd_mazo1.setLocationRelativeTo(this);
        jd_mazo1.setVisible(true);
    }//GEN-LAST:event_jmi_mazo1ActionPerformed

    private void jmi_mazo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mazo2ActionPerformed
        // TODO add your handling code here:
        jd_mazo2.setModal(true);
        jd_mazo2.pack();
        jd_mazo2.setLocationRelativeTo(this);
        jd_mazo2.setVisible(true);
    }//GEN-LAST:event_jmi_mazo2ActionPerformed

    private void jmi_mazo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mazo3ActionPerformed
        // TODO add your handling code here:
        jd_mazo3.setModal(true);
        jd_mazo3.pack();
        jd_mazo3.setLocationRelativeTo(this);
        jd_mazo3.setVisible(true);
    }//GEN-LAST:event_jmi_mazo3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (cmb_mazo1.getSelectedIndex()>=0) {
                DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_mazo1.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
                
                DefaultComboBoxModel modeloCMB = (DefaultComboBoxModel) cmb_mazo1.getModel();
                String tipo="",nombre="";
                int dano,p_vida,c_elix = 0,coste,cant=1,sum=0;
                dano=(((Carta)cartas.get(cmb_mazo1.getSelectedIndex())).getDano());
                p_vida=(((Carta)cartas.get(cmb_mazo1.getSelectedIndex())).getP_vida());
                nombre=(((Carta)cartas.get(cmb_mazo1.getSelectedIndex())).getNombre());
                if (cmb_mazo1.getSelectedItem().getClass().getSimpleName().equals("Minipekka")) {
                    tipo="Expecial";
                    c_elix=4;
                }
                
                if (cmb_mazo1.getSelectedItem().getClass().getSimpleName().equals("Montapuerco")) {
                    tipo="Especial";
                    c_elix=4;
                }
                
                if (cmb_mazo1.getSelectedItem().getClass().getSimpleName().equals("Golem")) {
                    tipo="Epica";
                    c_elix=8;
                }
                
                if (cmb_mazo1.getSelectedItem().getClass().getSimpleName().equals("Lenador")) {
                    tipo="Legendaria";
                    c_elix=4;
                }
                if (cmb_mazo1.getSelectedItem().getClass().getSimpleName().equals("Dragon_inf")) {
                    tipo="Legendaria";
                    c_elix=4;
                }
                
                if (cmb_mazo1.getSelectedItem().getClass().getSimpleName().equals("Dragon")) {
                    tipo="Epica";
                    c_elix=6;
                }
                
                if (cmb_mazo1.getSelectedItem().getClass().getSimpleName().equals("Gigante_nob")) {
                    tipo="Comun";
                    c_elix=6;
                }
                
                if (cmb_mazo1.getSelectedItem().getClass().getSimpleName().equals("Pandilla_duendes")) {
                    tipo="Comun";
                    c_elix=3;
                }
                
                sum=c_elix;
                coste=sum/cant;
                int c = -1;
                
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().equals(tipo)) {
                        for (int j = 0; j <  raiz.getChildAt(i).getChildCount(); j++) {
                        if (raiz.getChildAt(i).getChildAt(j).toString().equals(nombre)&&raiz.getChildAt(i).toString().equals(tipo)) {
                            i=raiz.getChildCount();
                            j=raiz.getChildAt(i).getChildAt(i).getChildCount();
                            
                        }
                    }
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Carta(nombre, dano, p_vida));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    c= 1;
                }
            }
                if (c == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(tipo);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Carta(nombre, dano, p_vida));
                n.add(p);
                raiz.add(n);
            }
            

            modeloArbol.reload();
            txt_coste1.setText(Integer.toString(coste));
            cant++;
            }
        } catch (Exception e) {
            System.out.println("Carta no puede ser agregada");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_agregarcarta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcarta2ActionPerformed
        // TODO add your handling code here:
        try {
            if (cmb_mazo2.getSelectedIndex()>=0) {
                DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_mazo2.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
                
                DefaultComboBoxModel modeloCMB = (DefaultComboBoxModel) cmb_mazo2.getModel();
                String tipo="",nombre="";
                int dano,p_vida;
                dano=(((Carta)cartas.get(cmb_mazo2.getSelectedIndex())).getDano());
                p_vida=(((Carta)cartas.get(cmb_mazo2.getSelectedIndex())).getP_vida());
                nombre=(((Carta)cartas.get(cmb_mazo2.getSelectedIndex())).getNombre());
                if (cmb_mazo2.getSelectedItem().getClass().getSimpleName().equals("Minipekka")) {
                    tipo="Expecial";
                }
                
                if (cmb_mazo2.getSelectedItem().getClass().getSimpleName().equals("Montapuerco")) {
                    tipo="Especial";
                }
                
                if (cmb_mazo2.getSelectedItem().getClass().getSimpleName().equals("Golem")) {
                    tipo="Epica";
                }
                
                if (cmb_mazo2.getSelectedItem().getClass().getSimpleName().equals("Lenador")) {
                    tipo="Legendaria";
                }
                if (cmb_mazo2.getSelectedItem().getClass().getSimpleName().equals("Dragon_inf")) {
                    tipo="Legendaria";
                }
                
                if (cmb_mazo2.getSelectedItem().getClass().getSimpleName().equals("Dragon")) {
                    tipo="Epica";
                }
                
                if (cmb_mazo2.getSelectedItem().getClass().getSimpleName().equals("Gigante_nob")) {
                    tipo="Comun";
                }
                
                if (cmb_mazo2.getSelectedItem().getClass().getSimpleName().equals("Pandilla_duendes")) {
                    tipo="Comun";
                }
                
                int c = -1;
                
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().equals(tipo)) {
                        for (int j = 0; j <  raiz.getChildAt(i).getChildCount(); j++) {
                        if (raiz.getChildAt(i).getChildAt(j).toString().equals(nombre)&&raiz.getChildAt(i).toString().equals(tipo)) {
                            i=raiz.getChildCount();
                            j=raiz.getChildAt(i).getChildAt(i).getChildCount();
                            
                        }
                    }
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Carta(nombre, dano, p_vida));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    c= 1;
                }
            }
                if (c == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(tipo);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Carta(nombre, dano, p_vida));
                n.add(p);
                raiz.add(n);
            }
            

            modeloArbol.reload();
            }
        } catch (Exception e) {
            System.out.println("Carta no puede ser agregada");
        }
    }//GEN-LAST:event_btn_agregarcarta2ActionPerformed

    private void btn_agregarcarta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcarta3ActionPerformed
        // TODO add your handling code here:
        try {
            if (cmb_mazo3.getSelectedIndex()>=0) {
                DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_mazo3.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
                
                DefaultComboBoxModel modeloCMB = (DefaultComboBoxModel) cmb_mazo3.getModel();
                String tipo="",nombre="";
                int dano,p_vida;
                dano=(((Carta)cartas.get(cmb_mazo3.getSelectedIndex())).getDano());
                p_vida=(((Carta)cartas.get(cmb_mazo3.getSelectedIndex())).getP_vida());
                nombre=(((Carta)cartas.get(cmb_mazo3.getSelectedIndex())).getNombre());
                if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Minipekka")) {
                    tipo="Expecial";
                }
                
                if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Montapuerco")) {
                    tipo="Especial";
                }
                
                if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Golem")) {
                    tipo="Epica";
                }
                
                if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Lenador")) {
                    tipo="Legendaria";
                }
                if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Dragon_inf")) {
                    tipo="Legendaria";
                }
                
                if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Dragon")) {
                    tipo="Epica";
                }
                
                if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Gigante_nob")) {
                    tipo="Comun";
                }
                
                if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Pandilla_duendes")) {
                    tipo="Comun";
                }
                
                int c = -1;
                
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().equals(tipo)) {
                        for (int j = 0; j <  raiz.getChildAt(i).getChildCount(); j++) {
                        if (raiz.getChildAt(i).getChildAt(j).toString().equals(nombre)&&raiz.getChildAt(i).toString().equals(tipo)) {
                            i=raiz.getChildCount();
                            j=raiz.getChildAt(i).getChildAt(i).getChildCount();
                            
                        }
                    }
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Carta(nombre, dano, p_vida));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    c= 1;
                }
            }
                if (c == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(tipo);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Carta(nombre, dano, p_vida));
                n.add(p);
                raiz.add(n);
            }
            

            modeloArbol.reload();
            }
        } catch (Exception e) {
            System.out.println("Carta no puede ser agregada");
        }
    }//GEN-LAST:event_btn_agregarcarta3ActionPerformed

    private void jt_mazo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_mazo1MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row=jt_mazo1.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_mazo1.setSelectionRow(row);
            Object v1 = jt_mazo1.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Carta) {
                carta_seleccionada = (Carta) nodo_seleccionado.getUserObject();
                popup_mostar1.show(evt.getComponent(),getX(),evt.getY());
            }
        }
    }//GEN-LAST:event_jt_mazo1MouseClicked

    private void jmi_mostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mostrar1ActionPerformed
        // TODO add your handling code here:
        String nombre,objetivo = "",velocidad= "",tipo= "",tip= "";
        int dano,p_vida,c_elixir=0;
        String total="";
        DefaultTreeModel m = (DefaultTreeModel) jt_mazo1.getModel();
        nombre = carta_seleccionada.getNombre();
        dano = carta_seleccionada.getDano();
        p_vida = carta_seleccionada.getP_vida();
        if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Minipekka")) {
            tipo = "Expecial";
            objetivo="Terrestre";
            velocidad="Alta";
            c_elixir=4;
            tip="Minipekka";
        }

        if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Montapuerco")) {
            tipo = "Especial";
            objetivo="Terrestre";
            velocidad="Alta";
            c_elixir=4;
            tip="Montapuerco";
        }

        if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Golem")) {
            tipo = "Epica";
            objetivo="Terrestre";
            velocidad="Baja";
            c_elixir=8;
            tip="Golem";
        }

        if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Lenador")) {
            tipo = "Legendaria";
            objetivo="Terrestre";
            velocidad="Alta";
            c_elixir=4;
            tip="Lenador";
        }
        if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Dragon_inf")) {
            tipo = "Legendaria";
            objetivo="Aereos";
            velocidad="Media";
            c_elixir=4;
            tip="Dragon Infernal";
        }

        if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Dragon")) {
            tipo = "Epica";
            objetivo="Aereo y terrestre";
            velocidad="Media";
            c_elixir=4;
            tip="Dragon";
        }

        if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Gigante_nob")) {
            tipo = "Comun";
            objetivo="Terrestre";
            velocidad="Media";
            c_elixir=6;
            tip="Gigante Noble";
        }

        if (cmb_mazo3.getSelectedItem().getClass().getSimpleName().equals("Pandilla_duendes")) {
            tipo = "Comun";
            objetivo="Terrestre y aereo";
            velocidad="Alta";
            c_elixir=3;
            tip="Pandilla de duendes";
        }
        
        JOptionPane.showMessageDialog(jd_mazo1, "Nombre: "+nombre+"\nDano: "+dano+"\nPuntos de vida: "+p_vida+"\nObjetivo: "+objetivo+"\nVelocidad: "+velocidad+"\nCoste de elixir: "+c_elixir+"\nTipo: "+tipo+"\nAtaque: "+tip);
    }//GEN-LAST:event_jmi_mostrar1ActionPerformed

    private void btn_crearclanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearclanActionPerformed
        // TODO add your handling code here:
        
        String nombre, userlider,tipo;
        Date f_creacion;
        
        nombre=txt_nombreequipo.getText();
        userlider=cmb_usuariolider.getSelectedItem().toString();
        tipo=cmb_tipoclan.getSelectedItem().toString();
        f_creacion=date_creacion.getDate();
        
        Clan cla = new Clan(nombre, f_creacion, userlider, tipo);
        
        clanes.add(cla);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_clanes.getModel();
        modelo.addElement(cla);
        cmb_clanes.setModel(modelo);
        
        

    }//GEN-LAST:event_btn_crearclanActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_clan.getModel();
        modelo.addElement(cmb_usuariolider1.getSelectedItem().toString());
        jl_clan.setModel(modelo);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jmi_ingresarclanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ingresarclanActionPerformed
        // TODO add your handling code here:
        jd_ingresarclan.setModal(true);
        jd_ingresarclan.pack();
        jd_ingresarclan.setLocationRelativeTo(this);
        jd_ingresarclan.setVisible(true);
    }//GEN-LAST:event_jmi_ingresarclanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarcarta;
    private javax.swing.JButton btn_agregarcarta2;
    private javax.swing.JButton btn_agregarcarta3;
    private javax.swing.JButton btn_agregarusuario;
    private javax.swing.JButton btn_color;
    private javax.swing.JButton btn_crearclan;
    private javax.swing.JComboBox<String> cmb_cartas;
    private javax.swing.JComboBox<String> cmb_clanes;
    private javax.swing.JComboBox<String> cmb_mazo1;
    private javax.swing.JComboBox<String> cmb_mazo2;
    private javax.swing.JComboBox<String> cmb_mazo3;
    private javax.swing.JComboBox<String> cmb_tipoclan;
    private javax.swing.JComboBox<String> cmb_usuariolider;
    private javax.swing.JComboBox<String> cmb_usuariolider1;
    private com.toedter.calendar.JDateChooser date_creacion;
    private com.toedter.calendar.JDateChooser date_fnacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog jd_agregarusuario;
    private javax.swing.JDialog jd_crearcarta;
    private javax.swing.JDialog jd_crearclan;
    private javax.swing.JDialog jd_ingresar;
    private javax.swing.JDialog jd_ingresarclan;
    private javax.swing.JDialog jd_m1;
    private javax.swing.JDialog jd_mazo1;
    private javax.swing.JDialog jd_mazo2;
    private javax.swing.JDialog jd_mazo3;
    private javax.swing.JList<String> jl_clan;
    private javax.swing.JMenu jmenu_carta;
    private javax.swing.JMenu jmenu_clan;
    private javax.swing.JMenu jmenu_mazo;
    private javax.swing.JMenu jmenu_usuario;
    private javax.swing.JMenuItem jmi_agregar;
    private javax.swing.JMenuItem jmi_crearcarta;
    private javax.swing.JMenuItem jmi_crearclan;
    private javax.swing.JMenuItem jmi_ingresar;
    private javax.swing.JMenuItem jmi_ingresarclan;
    private javax.swing.JMenuItem jmi_mazo1;
    private javax.swing.JMenuItem jmi_mazo2;
    private javax.swing.JMenuItem jmi_mazo3;
    private javax.swing.JMenuItem jmi_mostrar1;
    private javax.swing.JPasswordField jpass_contrasena;
    private javax.swing.JTree jt_mazo1;
    private javax.swing.JTree jt_mazo2;
    private javax.swing.JTree jt_mazo3;
    private javax.swing.JPopupMenu popup_mostar1;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_contranueva;
    private javax.swing.JTextField txt_coste1;
    private javax.swing.JTextField txt_danio;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombrecarta;
    private javax.swing.JTextField txt_nombreequipo;
    private javax.swing.JTextField txt_nusuario;
    private javax.swing.JTextField txt_pvida;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

ArrayList <Usuario> usuarios = new ArrayList();
ArrayList <Carta> cartas = new ArrayList();
ArrayList <Clan> clanes = new ArrayList();
DefaultMutableTreeNode nodo_seleccionado;
Carta carta_seleccionada;
}
